#!/bin/sh
##
## This file is part of the sigrok-util project.
##
## Copyright (C) 2016-2018 Uwe Hermann <uwe@hermann-uwe.de>
## Copyright (C) 2026 Steve Markgraf <steve@steve-m.de>
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, see <http://www.gnu.org/licenses/>.
##

#
# This script builds sigrok natively on MSYS2. It supports the UCRT64
# and CLANG64 environments. It can be run interactively (with 'prepare'
# to install dependencies) or non-interactively inside the MSYS2 Docker
# container via sigrok-msys2-docker.
#
# Usage:
#   ./sigrok-native-msys2 prepare  - install dependencies
#   ./sigrok-native-msys2          - build everything
#

set -e

# The base path prefix where the compiled packages will be installed.
PREFIXBASE=$HOME/sr_msys2

# The base path prefix where to download files to and where to build packages.
BUILDBASE=./build

# The $PREFIX subdir where the libsigrok Python bindings will be installed.
PYBASE=lib/python3/site-packages

# Edit this to control verbose build output.
# V="V=1 VERBOSE=1"

# Edit this to enable/disable/modify parallel compiles.
PARALLEL="-j $(nproc)"

# Edit this to enable/disable debug builds.
DEBUG=0

# You usually don't need to change anything below this line.

# -----------------------------------------------------------------------------

# Abort if the user runs the script in an "MSYS2 MSYS" shell.
if [ "$MSYSTEM" = "MSYS" ]; then
	echo "Building in an 'MSYS2 MSYS' shell will not work, aborting."
	echo "Please use an 'MSYS2 UCRT64' or 'MSYS2 CLANG64' shell."
	exit 1
fi

# The build target type: "x86_64" or "aarch64"
TARGET=$MSYSTEM_CARCH

GIT_CLONE="git clone --depth=1"
REPO_BASE="git://sigrok.org"

# Construct the build and install directory pathnames.
SUFFIX="x86-64"

if [ $DEBUG = 1 ]; then
	# CFLAGS/CXXFLAGS contains "-g" per default for autotools projects.
	BUILD_TYPE="Debug"
	PREFIX=$PREFIXBASE"_debug_"$SUFFIX
	BUILDDIR=$BUILDBASE"_debug_"$SUFFIX
else
	BUILD_TYPE="Release"
	PREFIX=$PREFIXBASE"_release_"$SUFFIX
	BUILDDIR=$BUILDBASE"_release_"$SUFFIX
fi

PYPATH=$PREFIX/$PYBASE

# Eliminate the host Python path environment variable, if any is set.
export PYTHONPATH=

# -----------------------------------------------------------------------------

P="$PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH"
C="--prefix=$PREFIX"
L="--disable-static --enable-shared"

MENV=""
if echo "$MSYSTEM" | grep -q "UCRT"; then
	MENV="ucrt-"
elif echo "$MSYSTEM" | grep -q "CLANG"; then
	MENV="clang-"
fi

W="mingw-w64-${MENV}${TARGET}"

echo "=== Environment: MSYSTEM=$MSYSTEM W=$W TARGET=$TARGET ==="
echo "=== PREFIX=$PREFIX BUILDDIR=$BUILDDIR ==="

# -----------------------------------------------------------------------------

if [ "x$1" = "xprepare" ]; then
  # Update package list, install/update all requirements.
  pacman --noconfirm -Suy
  pacman --noconfirm -S \
	git $W-autotools libtool make pkg-config wget patch zip \
	$W-toolchain $W-glib2 $W-glibmm $W-libusb $W-libftdi $W-check $W-boost \
	$W-libzip $W-doxygen $W-python $W-python-numpy $W-python-gobject \
	$W-python-setuptools $W-swig $W-cmake $W-nsis \
	$W-qt6-base $W-qt6-tools $W-qt6-svg $W-autotools \
	$W-libpng $W-libwebp $W-hidapi $W-sdcc
  exit
fi

mkdir -p $PYPATH

# Remove build directory contents (if any) and create a new build dir.
rm -rf $BUILDDIR
mkdir $BUILDDIR
cd $BUILDDIR

# -----------------------------------------------------------------------------

# libserialport
echo "=== Building libserialport ==="
$GIT_CLONE $REPO_BASE/libserialport
cd libserialport
./autogen.sh
mkdir build
cd build
../configure $C $L
make $PARALLEL $V
make install $V
cd ../..

# libsigrok
echo "=== Building libsigrok ==="
$GIT_CLONE $REPO_BASE/libsigrok
cd libsigrok

# Apply patch for COFF section ordering and dllexport.
# This enables building with both GCC (UCRT64) and Clang/lld (CLANG64).
echo "=== Patching libsigrok ==="
git apply ~/libsigrok-coff-section-ordering.patch

./autogen.sh
mkdir build
cd build
PKG_CONFIG_PATH=$P PYTHON=python3 ../configure $C $L --disable-python
make $PARALLEL $V
PYTHONPATH=$PYPATH make install $V
cd ../..

# libsigrokdecode
echo "=== Building libsigrokdecode ==="
$GIT_CLONE $REPO_BASE/libsigrokdecode
cd libsigrokdecode
./autogen.sh
mkdir build
cd build
PKG_CONFIG_PATH=$P ../configure $C $L
make $PARALLEL $V
make install $V
cd ../..

# sigrok-firmware
echo "=== Building sigrok-firmware ==="
$GIT_CLONE $REPO_BASE/sigrok-firmware
cd sigrok-firmware
./autogen.sh
mkdir build
cd build
# Nothing gets cross-compiled here, we just need 'make install' basically.
../configure $C
make install $V
cd ../..

# sigrok-firmware-fx2lafw
echo "=== Building sigrok-firmware-fx2lafw ==="
$GIT_CLONE $REPO_BASE/sigrok-firmware-fx2lafw
cd sigrok-firmware-fx2lafw
./autogen.sh
./configure --prefix=$PREFIX
make $PARALLEL $V
make install $V
cd ..

# sigrok-cli
echo "=== Building sigrok-cli ==="
$GIT_CLONE $REPO_BASE/sigrok-cli
cd sigrok-cli
./autogen.sh
mkdir build
cd build
PKG_CONFIG_PATH=$P ../configure $C $L
make $PARALLEL $V
make install $V
cd ../..

# PulseView
echo "=== Building PulseView ==="
$GIT_CLONE $REPO_BASE/pulseview
cd pulseview
git apply ~/pulseview.patch
mkdir build
cd build
PKG_CONFIG_PATH=$P cmake \
	-G "Unix Makefiles" \
	-DCMAKE_INSTALL_PREFIX:PATH=$PREFIX \
	-DCMAKE_BUILD_TYPE=$BUILD_TYPE \
	-DDISABLE_WERROR=y \
	-DENABLE_TESTS=n \
	..
make $PARALLEL $V
make install $V
cd ../..

# -----------------------------------------------------------------------------

# Install required libraries
echo "=== Gathering release files ==="
pushd $PREFIX/bin
ldd sigrok-cli.exe | grep $MSYSTEM_PREFIX | awk '{print $3}' | xargs -i cp {} .
ldd pulseview.exe | grep $MSYSTEM_PREFIX | awk '{print $3}' | xargs -i cp {} .
cp $MSYSTEM_PREFIX/bin/Qt6Svg.dll .
cp -r $MSYSTEM_PREFIX/share/qt6/plugins/platforms .
cp -r $MSYSTEM_PREFIX/share/qt6/plugins/styles .
cp -r $MSYSTEM_PREFIX/share/qt6/plugins/iconengines .

# Copy Python related files
mkdir -p lib
cp -r $MSYSTEM_PREFIX/lib/python3* lib/
rm -rf lib/python*/test
find lib/ -path '*/__pycache__*' -delete

mkdir -p share
cp -r ../share/libsigrokdecode share/
cp -r ../share/sigrok-firmware share/

zip -r ../sigrok-msys2-release.zip *

# -----------------------------------------------------------------------------

# Download Zadig and build NSIS installer
echo "=== Downloading Zadig 2.9 ==="
wget -q https://github.com/pbatard/libwdi/releases/download/v1.5.1/zadig-2.9.exe \
	-O zadig.exe

echo "=== Preparing NSIS installer ==="
cp ~/sigrok-installer.nsi .
cp ~/FileAssociation.nsh .

# Copy PulseView icon and license for the installer
PVSRC=$(find $HOME -maxdepth 3 -name "pulseview" -type d | head -1)
cp $PVSRC/icons/pulseview.ico .
cp $PVSRC/COPYING .

# Determine version string
PVVERSION=$(cd $PVSRC && git describe --always 2>/dev/null || echo "unknown")
VERSION=$(date +%Y%m%d)-$PVVERSION-$MSYSTEM

echo "=== Building NSIS installer (version: $VERSION) ==="
makensis -DPE64=1 -DVERSION=$VERSION sigrok-installer.nsi

# Move installer to a known location for easy extraction
mv sigrok-*-installer.exe ~/sigrok-installer.exe

popd

echo "=== Build complete ==="
